// Copyright 2026 Slick Quant
// SPDX-License-Identifier: MIT
//
// Generated by CMake from cmake/version.hpp.in -- do not edit, and do not
// delete: it is committed so that `include/` stands on its own for anyone
// consuming the headers without CMake.
//
// To change the version, edit the `project()` call in the top-level
// CMakeLists.txt -- the one place it is written down -- then configure, and
// commit the result alongside it.

#pragma once

#define SLICK_STACKER_VERSION_MAJOR 0
#define SLICK_STACKER_VERSION_MINOR 1
#define SLICK_STACKER_VERSION_PATCH 0

#define SLICK_STACKER_VERSION_STRING "0.1.0"

/// The three parts as one integer, so a dependent can gate on a release:
/// `#if SLICK_STACKER_VERSION >= 10200` for 1.2.0 or later.
#define SLICK_STACKER_VERSION                                              \
    (SLICK_STACKER_VERSION_MAJOR * 10000 + SLICK_STACKER_VERSION_MINOR * 100 + \
     SLICK_STACKER_VERSION_PATCH)
